TOR_BINARY_PATH = "firefox_tor"
TOR_BUNDLE_PATH = "/home/user/.tb/tor-browser"
MOZILLA_BINARY_PATH = "firefox"
CHROME_BINARY_PATH = "chromium"
EDGE_CHROMIUM_BINARY_PATH = "edge"
OPERA_BINARY_PATHS = "opera"